version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-db
    image: ssgaikwad/pratice-db
    volumes:
      - vprodbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: vprodb
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
    
  vprocache01:
    image: memcached
    ports: 
      - "11211:11211"
    container_name: memcached

  vpromq01:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproweb:
    build:
      context: ./Docker-web
    ports:
      - "80:80"
    container_name: vproweb
    image: ssgaikwad/pratice-web
  
  vproapp:
    build: 
      context: ./Docker-app
    ports:
      - "8080:8080"
    container_name: vproapp
    image: ssgaikwad/pratice-app
    volumes:
      - vproappdata/usr/local/tomcat/webapps

volumes:
  vproappdata: {}
  vprodbdata: {}
